### ISSUE TITLE
Node.run can hang indefinitely on long code strings

### ISSUE THREAD

**Issue by ccmcintyre-kingsds** [Kings-Distributed-Systems/Bifrost#11]
Encountered when passing a string of JS code of length 9344 (note: mult of 2,4,8,16,32,64,128) to be evaled by node.run. This effect MAY accumulate across multiple calls of node.run (hinted but not verified), but irregardless [sic] is primarily caused by length of strings being directly passed to node.run, NOT by other variables currently being synced (problem triggers at identical spot in both a relatively fresh run AND when the scope has been weighed down by syncing complex cloudpickle objects; makes no difference).

**Here's where it is getting lost:**
(_everything prior in node.run proceeds successfully, and the subsequent timeout will trigger successfully if set_)
```#py_nodejs.py
        while flag:
            try:
                NODE_LOCK.acquire_read()
                flag = NODE_IS_RUNNING
                NODE_LOCK.release_read()
```

**Comment by ccmcintyre-kingsds** [comment]
Increasing evidence that this effective is cumulative, at least for recent multi-job runs on Windows and Ubuntu using the `windows` build (relies on file-mmapping). Needs further investigation.

**Comment by ccmcintyre-kingsds** [comment]
Investigations have been done by @alexsalgokds to map the contextual boundaries and origins of this bug more thoroughly; a fix informed by these is pending.

**Comment by ccmcintyre-kingsds** [comment]
Failure is always preceded by a "false" being returned from `this.push(chunk);` in the stream._transform function.
https://nodejs.org/api/stream.html#readablepushchunk-encoding

**Comment by ccmcintyre-kingsds** [comment]
**Problem Identified**
The repeated calls to node.run are hitting the `highWaterMark` threshold of the stream by filling it up with chunks that aren't being dealt with. This causes the stream to halt until enough data is removed from the pipe that it falls below the threshold (which will not happen, since the data clogging it is being ignored).

While most data related to the nodejs processes is being properly addressed (stdin, stdout, stderr), theoretically keeping the stream clear, there is one category of data that is being allowed to accumulate without further engagement: the strings of JS code being passed to each call to node.run. When the length of the sum of all strings passed to all calls of node.run over the course of a single stream exceeds the value of the stream's `highWaterMark`, the stream will return "false" on a call to `this.push(chunk)`, and the next attempt to use that stream (ie the next call to node.run) will halt upon starting and loop without feedback indefinitely (or until it times out, if the user passed a timeout value to node.run).

_Note to self and others_: identifying this was made somewhat slower and more confusing due to the necessity of navigating the insidiously pythonic "try/except control structure". We are going to purge any such patterns from this repo eventually, mark my words. I have a creeping feeling that the constant intentional error-consumption-as-control-flow might not just be obfuscating problems, but **causing** them.

**Solutions Identified (Pick Your Favourite)**
1 - Remove the previous JS code strings from the stream after each run
2 - Occasionally purge or drain everything in the pipe, just in case
3 - Set an absurdly high value for `highWaterMark` and hope for the best
_Probably do the first one._

**Comment by 11mhg** [comment]
Totally agree. If I could rewrite this, I would rewrite the try/except control structure. It's a holdover of time constraints and project constraints and shouldn't be part of a well-oiled final product. Thanks for figuring this out @ccmcintyre-kingsds !
