### ISSUE TITLE
Importing Libraries Improvement

### ISSUE THREAD

**Issue by Jonah1234567** [Kings-Distributed-Systems/Bifrost#37]
When importing libraries, a user needs to specify the libraries being used within the work function via import statements and also require those libraries afterwards with a job.require statement. In addition, the user must also require all of the dependencies of the libraries they are using. Here is an example of this in practice: 

```
def work_function(input_params):
  # Import datasets, classifiers and performance metrics
  from sklearn import datasets, svm, metrics
  from sklearn.neural_network import MLPClassifier
  from sklearn.model_selection import train_test_split

job = dcp.compute_for(configs, work_function)

job.requires("numpy")
job.requires("scikit-learn")
job.requires("scipy")
job.requires("joblib")
job.requires("threadpoolctl")
```

Instead of having two different places for imports, there should only be one place for specifying libraries used in the work function (preferably the import statement in the work function). In addition, the user should not be required to include each libraries dependencies.

**Comment by ccmcintyre-kingsds** [comment]
The solution to this touches almost every part of our Python deployment stack, but in consistently small and straightforward ways; as such, I personally consider it a very good introductory issue for getting acquainted with a wide cross-section of Bifrost's components without being overwhelmed by complexity.

**Comment by ccmcintyre-kingsds** [comment]
What we should really do, especially now that Pyodide 21 is viable, is explicitly make every Python library into a BravoJS module, inside the worker or otherwise... they *pieces* of them already are, technically, in order to get them gracefully into the worker, but I'm thinking of wrapping the re-assembled python code in a BravoJS / CommonJSv2.0 module.declare, populate the dependencies for each of them from Pyodide's own existing dependency list (conveniently already JSON formatted), and hook up the Pyodide initialization to our `requires` by whatever paths it wants to take, rather than using those paths to serve up requested web assembly binaries explicitly+directly. In fact, if we're clever about namespacing and the initial job requirements, this could be a very concise way of making user-provided dependencies as a problem-space entirely disappear.

**Comment by ccmcintyre-kingsds** [comment]
Current work on this is nearing completion and will spec out as follows (with reference to the original issue):
- `the user should not be required to include each libraries dependencies` : satisfied : the user will not have to specify (or even know) any dependencies of Pyodide libraries being used; Bifrost is being given the functionality to track and manage all dependency retrieval (source of truth will be Pyodide's `repodata.json`).
- `there should only be one place for specifying libraries used in the work function` : subversively satisfied : only one place is required, but we are in fact exposing many locations where that can be (`job.requires`, `job.imports`, `import` in worker function). We assume that the user will be using `import` in their worker function to the same degree as usual for Python, but to accomodate scope, we have a feature being exposed in this branch (via job.imports) that will allow them to specify Python modules, whether local in their system or remote on our package manager (in future maybe even pypi via micropip?), that are not explicitly imported in their work function, but that need to be made available to it nonetheless. This requirement could most often be expected to come up as a result of work functions being distributed that were not written for distributed computing environments, and so their dependencies were not scoped accordingly.

Further potential improvements:
- Pyodide exposes functionality for automatically determining what needs to be made available to a given Python script, via analysis of the import statements. Cloudpickle meanwhile has extremely powerful automated dependency identification and edge-friendly serialization. Used cleverly, these features can facilitate further reduction of the user's need to specify their application dependencies, conceivably down from "in at least one of several available places", to, "zero intervention required". The UX potential here is very strong.
