### ISSUE TITLE
Library Naming Convention

### ISSUE THREAD

**Issue by Jonah1234567** [Kings-Distributed-Systems/Bifrost#38]
There are some minor issues with the naming conventions for certain Python libraries. For instance to import the scikit-learn library the statement `import sklearn` is required to complete this task. However to require the library, `job.requires("scikit-learn")` is used. Both the job.require and the import statement should reference the same name rather than two separate ones. The name used should be the same one as is used in the pythonic import statement as users will be familiar with this.

**Comment by ccmcintyre-kingsds** [comment]
Issue becomes redundant once #37 (automatic library imports and dependency resolution) is implemented. That ticket is an easy fix, in both design and implementation, whereas "fixing" the naming convention used by the job handle to be in-line with the python import statements is extremely difficult as a design challenge. Not even the actual CPython ecosystem acts in line with the expectations of this ticket. Staying aligned with Pyodide's naming system, and accomodating the namespace restrictions of the current DCP package management system, add further complexity to this conceptual challenge. Strongly recommend using Python imports as per #37 to circumvent this entire problem space, and in future, if revisited, prefer micropip and/or pip naming for job.requires (in line with Hamada's suggestions), even if those conflict with the names used by import statements.

**Comment by Jonah1234567** [comment]
Yeah that makes sense to me, if you only need the import statement then this becomes redundant. I'm ok to close this issue if you are
