### ISSUE TITLE
Suggest adding an Issue templates

### ISSUE THREAD

**Issue by 11mhg** [Kings-Distributed-Systems/Bifrost#48]
I suggest an issue template be added to the Github to standardize the issue submission process and formalize information to be collected before issue submission.

Perhaps using something like the new issue forms from GitHub would make it even easier: [Github Docs Link on issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms). 

If you're curious as to what that looks like check out these [Tensorflow Issue Forms for inspiration.](https://github.com/tensorflow/tensorflow/issues/new/choose)

**Comment by ccmcintyre-kingsds** [comment]
Resolved by #92
